### ISSUE TITLE
Drive System - Power Regulation

### ISSUE THREAD

**Issue by Talonj123** [m2i/MAVRIC-Electrical#6]
Our current power needs for the DC motor bus peak at just shy of 550 Amps at 12 V, that's 6.6 kW. My searches have not revealed any regulators that fit a viable form factor and also provide that much juice. With our regulators from last year, we would need 46 of them in parallel to get this much throughput.

Does anyone have thoughts on getting that much juice or how to reduce the requirement?
I don't know how to get a nominal load for the motors, can I just take some percentage of the stall load? If so, what percentage?

**Comment by Talonj123** [comment]
@matgyver, Any words of wisdom?

**Comment by Talonj123** [comment]
Would 24V motors be better?

**Comment by matgyver** [comment]
Yes, the higher the voltage the lower your current goes (P=VI).  6.6 kw seems high, what is the torque requirements for the motors?  Is that peak or continuous?

**Comment by Talonj123** [comment]
The 6.6 kW comes from stall. I know that's not normal operating conditions, but I don't want the rover to burn out if something goes wrong.

|              | Stall        | Rated        |
|----------|-----------|------------|
| Torque  | 70 oz-in | 7.86 oz-in |
| Current | 85 A        | ? [not given] |

**Comment by Talonj123** [comment]
We don't currently have a defined requirement for how much torque we need out of the motors. For the most part, our issue has been ground slippage, not motor power, though I didn't see it on the hills at competition, where the ground might be harder.

**Comment by Talonj123** [comment]
More information on motors/power:
It looks like the voltage will define the speed the motor goes at (might be for brushed DC only) while the current is consumed proportional to output power (torque*speed). Using an ESC with brushless DC motors might give us good control of speed, but it will likely try to accelerate quickly (max torque). As such, we might want to ramp the speed so that the acceleration is limited, that way we don't use too much current.

@jraymer1 Can you confirm/reject any of this? I haven't done the research directly, just put some things together from other people.

**Comment by Talonj123** [comment]
We have decided to operate the drive motors directly off the battery, so this is a non-issue.
